spring:
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        boot:
          allow_jdbc_metadata_access: false
  main:
    allow-bean-definition-overriding: true
security:
  add-mapping: "/**"
  allowed-headers:
    - "*"
  allowed-origins: "http://localhost:3000,http://localhost:3001,http://localhost:8086"
  allow-credentials: true
  issuer-uri: "http://localhost:8088"
  max-age: 600
  permit-all: ["*"]
  allowed-methods:
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
    - "PATH"
    - "OPTIONS"
saga:
  swagger:
    list-server: [ "http://localhost:8085,Server swagger localhost","http://localhost:8086,Server swagger localhost" ]
    description: Product api
    license-name: "Saga license"
database:
  enable: true
  url: "jdbc:mysql://localhost:3306/product"
  username: "root"
  password: "123456aA@"
  driver: "com.mysql.cj.jdbc.Driver"
  type: "com.zaxxer.hikari.HikariDataSource"
  auto-commit: true
  pool-name: "mysql-pool"
  max-pool-size: 20
  min-pool-size: 3
  properties:
    cachePrepStmts: "true"
    prepStmtCacheSize: "250"
    prepStmtCacheSqlLimit: "2048"
    useServerPrepStmts: "true"
kafka:
  boot-strap-server: "localhost:29092"
  group-id: "saga"
server:
  port: 8085
springdoc:
  api-docs:
    enabled: true
    #path: /disable
  swagger-ui:
    enabled: true
  writer-with-order-by-keys: true



