spring:
  jpa:
    hibernate.ddl-auto: none
    generate-ddl: true
    show-sql: false
    open-in-view: off
  web:
    resources:
      add-mappings: true
      static-locations: classpath:/static/
database:
  enable: true
  url: "jdbc:mysql://localhost:3306/iam"
  username: "root"
  password: "123456"
  driver: "com.mysql.cj.jdbc.Driver"
  type: "com.zaxxer.hikari.HikariDataSource"
  auto-commit: true
  pool-name: "mysql-pool"
  max-pool-size: 20
  min-pool-size: 3
  properties:
    cachePrepStmts: "true"
    prepStmtCacheSize: "250"
    prepStmtCacheSqlLimit: "2048"
    useServerPrepStmts: "true"
server:
  port: 8088
  servlet:
    session:
      timeout: 10m
      tracking-modes: cookie
      cookie:
        http-only: true
        secure: true
logging:
  level:
    org.springframework.web: INFO
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG