spring:
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
  main:
    allow-bean-definition-overriding: true
    lazy-initialization: true
database:
  enable: true
  url: "jdbc:mysql://localhost:3306/orders"
  username: "root"
  password: "123456"
  driver: "com.mysql.cj.jdbc.Driver"
  type: "com.zaxxer.hikari.HikariDataSource"
  auto-commit: true
  pool-name: "mysql-pool"
  max-pool-size: 20
  min-pool-size: 3
  properties:
    cachePrepStmts: "true"
    prepStmtCacheSize: "250"
    prepStmtCacheSqlLimit: "2048"
    useServerPrepStmts: "true"
server:
  port: 8080
kafka:
  boot-strap-server: "localhost:29092"
  group-id: "saga"
