spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/inventory
    username: root
    password: 123456
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
grpc:
  server:
    port: 9091
  client:
    hello:
      address: localhost:9090
      negotiation-type: plaintext
server:
  port: 8081
