spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/orchestration_order
    username: root
    password: 123456
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
grpc:
  server:
    port: 9090
  client:
    inventory:
      address: localhost:9091
      negotiation-type: plaintext
server:
  port: 8086
