spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo
    username: root
    password: 123456aA@
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
