spring:
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
  main:
    allow-bean-definition-overriding: true
database:
  enable: true
  url: "jdbc:mysql://localhost:3306/iam"
  username: "root"
  password: "123456aA@"
  driver: "com.mysql.cj.jdbc.Driver"
  type: "com.zaxxer.hikari.HikariDataSource"
  auto-commit: true
  pool-name: "mysql-pool"
  max-pool-size: 20
  min-pool-size: 3
  properties:
    cachePrepStmts: "true"
    prepStmtCacheSize: "250"
    prepStmtCacheSqlLimit: "2048"
    useServerPrepStmts: "true"
grpc:
  server:
    port: 9092
server:
  port: 9000
kafka:
  boot-strap-server: "localhost:29092"
  group-id: "admin"
  properties-consumer:
    max.poll.records: 1000
springdoc:
  api-docs:
    enabled: true
    #path: /disable
  swagger-ui:
    enabled: true
  writer-with-order-by-keys: true
saga:
  swagger:
    list-server: [ "http://localhost:9000,Server swagger localhost" ]
    description: Admin api
    license-name: "Saga license"
security:
  add-mapping: "/**"
  allowed-headers:
    - "*"
  allowed-origins: "http://localhost:3000,http://localhost:3001"
  allow-credentials: true
  issuer-uri: "http://localhost:8088"
  max-age: 600
  permit-all: ["*"]
  allowed-methods:
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
    - "PATH"
    - "OPTIONS"